version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Using Cloud MongoDB, so no need for local db service
      DATABASE_URL: mongodb+srv://change20U:YkliB3wirfhVJFVC@change20dev.uj6bor5.mongodb.net/
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BASE_URL: https://devwebinar.change20.no
      DEBUG: "True"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
